(deftheme ayu-night-owl
  "Created 2018-10-01.")

(custom-theme-set-faces
 'ayu-night-owl
 '(default ((t (:family "Fira Code" :foundry "nil" :width normal :height 120 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#D6DEEB" :background "#011627" :stipple nil :inherit nil))))
 '(cursor ((t (:foreground "#D6DEEB" :background "#80A4C2"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#637777"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#82AAFF"))))
 '(highlight ((t (:background "#1D3B53"))))
 '(region ((t (:background "#1D3B53" :inherit (highlight)))))
 '(shadow ((t (:foreground "#637777"))))
 '(secondary-selection ((t (:background "#3C5B74" :inherit (region)))))
 '(trailing-whitespace ((t (:background "#C792EA"))))
 '(font-lock-builtin-face ((t (:weight normal :foreground "#C792EA"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#637777"))))
 '(font-lock-comment-face ((t (:foreground "#637777"))))
 '(font-lock-constant-face ((t (:foreground "#7E57C2"))))
 '(font-lock-doc-face ((t (:foreground "#ECC48D"))))
 '(font-lock-function-name-face ((t (:foreground "#82AAFF"))))
 '(font-lock-keyword-face ((t (:weight normal :foreground "#C792EA"))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#FFEB95"))))
 '(font-lock-preprocessor-face ((t (:foreground "#EF5350"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight normal :foreground "#7E57C2"))))
 '(font-lock-regexp-grouping-construct ((t (:weight normal :foreground "#FFEB95"))))
 '(font-lock-string-face ((t (:foreground "#ECC48D"))))
 '(font-lock-type-face ((t (:slant normal :foreground "#82AAFF"))))
 '(font-lock-variable-name-face ((t (:foreground "#ADDB67"))))
 '(font-lock-warning-face ((t (:weight bold :slant italic :underline (:color foreground-color :style line) :foreground "#F78C6C"))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#82AAFF"))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#7E57C2"))))
 '(fringe ((t (:foreground "#D6DEEB" :background "#011627"))))
 '(header-line ((t (:box (:line-width 1 :color "#5F7E97" :style unspecified) :foreground "#FFFFFF" :background "#1D3B53"))))
 '(tooltip ((t (:foreground "#011627" :background "#FFF9DC" :inherit (default)))))
 '(mode-line ((t (:box (:line-width 1 :color "#0B2942" :style nil) :foreground "#D6DEEB" :background "#0B2942"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#D6DEEB"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box nil))))
 '(mode-line-inactive ((t (:box (:line-width 1 :color "#5F7E97" :style nil) :foreground "#676E95" :background "#011627"))))
 '(isearch ((t (:foreground "#011627" :background "#FFEB95" :inherit (region)))))
 '(isearch-fail ((t (:weight bold :foreground "#C792EA" :background "#011627" :inherit (isearch)))))
 '(lazy-highlight ((t (:background "#3C5B74" :inherit (highlight)))))
 '(match ((t (:weight bold :foreground "#011627" :background "#F78C6C"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'ayu-night-owl)
